my_name = ('Danel', 'Machulskiy', 20)
people = []
people.append(my_name)
friend_1 = ('Betty', 'Green', 21)
friend_2 = ('Mari', 'Adamson', 18)
friend_3 = ('Paul', 'Fisher', 19)
people.append(friend_1)
people.append(friend_2)
people.append(friend_3)
print('Несортированный список:')
print(people)
print('Сортировка по имени:')
people.sort(key = lambda x: x[0])
print(people)
print('Сортировка по возрасту:')
people.sort(key = lambda x: x[2])
print(people)
print('Сортировка по фамилии:')
people.sort(key = lambda x: x[1])
print(people)